# 基本站点信息
title: "Your Name"
description: "Personal academic & project portfolio"
lang: en
timezone: Europe/London
url: "https://yourusername.github.io"
baseurl: ""     # 用户主页必须为空

# 主题（可设为 null 表示自定义样式）
theme: null
plugins:
  - jekyll-seo-tag

# 个人信息
name: "Your Name"
avatar: "/assets/images/avatar.jpg"   # 放头像文件路径
bio: "A motivated robotics and AI researcher passionate about computer vision, knowledge graphs, and intelligent construction safety management."

# 技能列表
skills:
  - Python / PyTorch / Machine Learning
  - Data Mining / NLP / Knowledge Graphs
  - Unity / ROS2 / Robotics
  - Web Development (HTML, CSS, JS)
  - Academic Writing (SCI papers)

# 职业目标或研究兴趣
career_objectives: |
  My research focuses on AI-driven safety knowledge modeling and organizational resilience in large-scale engineering projects.
  I aim to bridge machine intelligence with real-world infrastructure safety management through interpretable AI and data-driven decision support.

# 项目与视频简介
projects:
  - title: "Shield Tunnel Safety Knowledge Graph"
    description: "An intelligent knowledge extraction and visualization framework for tunneling safety management."
    pdf: "/assets/pdfs/tunnel_kg.pdf"
    video: "/assets/videos/tunnel_kg.mp4"
    link: "https://github.com/yourusername/shield-tunnel-kg"
  - title: "Organizational Resilience Simulation"
    description: "Dynamic Bayesian modeling of project resilience under extreme events."
    pdf: "/assets/pdfs/resilience_simulation.pdf"
    video: "https://www.youtube.com/embed/yourVideoID"
    link: "https://github.com/yourusername/org-resilience"

# 外部链接（至少两个）
links:
  github: "https://github.com/yourusername"
  linkedin: "https://www.linkedin.com/in/yourusername/"
  cv: "/assets/docs/CV.pdf"

# 页脚信息
footer: "© {{ 'now' | date: '%Y' }} Your Name — Personal Website"
